### ISSUE TITLE
执行不了国产化命令

### ISSUE THREAD

**Issue by zhizi01** [qxchuckle/vsc-cec-ide#17]
执行不了国产化命令

**Comment by nebulachinese** [comment]
![QQ截图20230828150447](https://github.com/qxchuckle/vsc-cec-ide/assets/88622750/003a9f6a-4dbb-4466-844f-f3f44cacfc9f)

**Comment by qxchuckle** [comment]
你应该ctrl + shift + p 使用vscode的命令，而不是在终端
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/14af1d72-87b6-4101-928a-8d684ca72d47)

**Comment by qxchuckle** [comment]
并且请确保以管理员身份运行VSCode

**Comment by nebulachinese** [comment]
![QQ截图20230828151323](https://github.com/qxchuckle/vsc-cec-ide/assets/88622750/860267a6-650e-4991-a5a2-275767f5aed9)
已经成功国产化了，很喜欢 😍😍😍

**Comment by nebulachinese** [comment]
什么时候开通充值入口😍😍😍

**Comment by qxchuckle** [comment]
> 什么时候开通充值入口😍😍😍

你可以尝试点击侧边栏的cec-ide图标，再点击激活会员（

**Comment by ThinkerOfJS** [comment]
> > 什么时候开通充值入口😍😍😍
> 
> 你可以尝试点击侧边栏的cec-ide图标，再点击激活会员（

6
