### ISSUE TITLE
最近将增加敏感词检测功能

### ISSUE THREAD

**Issue by qxchuckle** [qxchuckle/vsc-cec-ide#19]
更好地助力开发者进行项目研发

**Comment by lihugang** [comment]
这敏感词库可不兴公开啊，小心一会儿就 451 Unavailable For Legal Reasons，不如给敏感词hash一下再匹配？

**Comment by qxchuckle** [comment]
> 这敏感词库可不兴公开啊，小心一会儿就 451 Unavailable For Legal Reasons，不如给敏感词hash一下再匹配？

注意到了该问题，将会对文件进行加密

**Comment by lihugang** [comment]
> 这敏感词库可不兴公开啊，小心一会儿就 451 Unavailable For Legal Reasons，不如给敏感词hash一下再匹配？

别成绿坝了😂

**Comment by so1ve** [comment]
https://github.com/qxchuckle/vsc-cec-ide/commit/8b54cbf5bd9739d837c5741d4860ff69d0bd5f9f

**Comment by qxchuckle** [comment]
已更新0.1.1版本，实装了敏感词检测，目前词库较为严格，有推荐的词库可以在此comment
