### ISSUE TITLE
希望在启动时增加"社会主义核心价值观"展示功能

### ISSUE THREAD

**Issue by CLOUDERHEM** [qxchuckle/vsc-cec-ide#24]
1. 社会主义核心价值观强调社会公平和公正，而在编写代码时，程序员应该遵循这一原则。他们应该设计和编写公平、公正的系统和应用程序，不歧视任何集群，确保集群资源的公平分配。

2. 社会主义核心价值观强调创新和进步，这对于编写代码来说同样重要。程序员需要不断学习新的编程语言、框架和技术，掌握最新的发展趋势，并通过创新思维和方法，提供更高效、安全和可靠的软件解决方案。

3. 社会主义核心价值观鼓励共享和开放的精神，在编写代码时也可以体现。程序员可以积极参与开源社区，分享自己的代码和知识，促进技术的交流与共享，推动整个行业的发展。

综上所述，社会主义核心价值观对于写代码具有重要影响。它引导程序员树立正确的价值观念，关注社会责任，推动技术的创新与进步，并通过合作与共享来实现更大的社会效益。编写符合社会主义核心价值观的代码，既是对国家、社会的贡献，也是对自身职业道德和责任感的体现。

**Comment by qxchuckle** [comment]
这只是一个整活插件，并且正在增加真正有用的，国产特色功能，如敏感词检测等
