### ISSUE TITLE
bug: 敏感词提示重复

### ISSUE THREAD

**Issue by lihugang** [qxchuckle/vsc-cec-ide#25]
如果文中有多个重复的敏感词，那么每处敏感词下面都会有多个提示，提示条数和敏感词在文中出现的次数相同

![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/0914894c-3010-47c0-9342-fc42d7e5e737)
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/0a2a6caf-ce8a-4865-a790-0f974bc7160a)

如图所示

**Comment by qxchuckle** [comment]
实际上已经修复了这一点，但还未推送，敏感词检测的逻辑正在大改，请稍等

**Comment by lihugang** [comment]
好，谢谢

**Comment by qxchuckle** [comment]
已经修复该问题并推送

**Comment by lihugang** [comment]
solved with d54450d
