### ISSUE TITLE
请添加学‘习’ ‘墙’国主题

### ISSUE THREAD

**Issue by 23BED7** [qxchuckle/vsc-cec-ide#36]
请添加学‘习’ ‘墙’国主题

**Comment by gkcoll** [comment]
> 请添加学‘习’ ‘墙’国主题

这个有啊，YouTube 上有：『墙国反贼』『波特王好帅』『墙国蛙呱呱』之类的，，

**Comment by qxchuckle** [comment]
本项目仅与vscode、cec-ide相关
