### ISSUE TITLE
不应在remote中安装

### ISSUE THREAD

**Issue by Asxcvbn** [qxchuckle/vsc-cec-ide#39]
该插件既然主要修改了本地文件，那么应当在本地运行，但是在remote中安装的话，默认会在remote端，而不是本地
![图片](https://github.com/qxchuckle/vsc-cec-ide/assets/63904802/46eaadef-c541-45f1-86ef-95813e0cec21)
这样在remote窗口安装后，运行命令会国产化失败。

**Comment by qxchuckle** [comment]
这似乎在加上"extensionKind": ["ui"],就行，但我不确定，我将试一试，如果你知道该如何修复，也请告诉我
