### ISSUE TITLE
[feature request] 找不到充值入口

### ISSUE THREAD

**Issue by rennsax** [qxchuckle/vsc-cec-ide#4]
无法充会员 VIP。

![image](https://github.com/qxchuckle/vsc-cec-ide/assets/93167100/0d048033-a8bd-4d10-a325-d6eebdce9171)

**Comment by qxchuckle** [comment]
正在完成该功能，这是国产化必不可少的核心技术，为了使其更加显眼，我将会将会员界面移动至侧边栏固定入口

**Comment by lihugang** [comment]
> 正在完成该功能，这是国产化必不可少的核心技术，为了使其更加显眼，我将会将会员界面移动至侧边栏固定入口

希望能出个外观调整的功能，可以选择**显眼版**（侧边栏固定入口）和**原汁原味版**（和cec-ide一样，在登录那里），用户可以自行调整，谢谢

**Comment by qxchuckle** [comment]
> > 正在完成该功能，这是国产化必不可少的核心技术，为了使其更加显眼，我将会将会员界面移动至侧边栏固定入口
> 
> 希望能出个外观调整的功能，可以选择**显眼版**（侧边栏固定入口）和**原汁原味版**（和cec-ide一样，在登录那里），用户可以自行调整，谢谢

vscode没有直接修改UI的api，不想用插件去改源码了，改那部分怕影响正常使用，还是扔侧边栏了（

![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/c919b7f0-eaad-4f81-9959-85e28d7c76e2)

**Comment by big-tooth** [comment]
> 正在完成该功能，这是国产化必不可少的核心技术，为了使其更加显眼，我将会将会员界面移动至侧边栏固定入口

支持充值，支持国产，支持华为。

**Comment by Mudust** [comment]
核心技术不能忘
