### ISSUE TITLE
快捷修复 不工作

### ISSUE THREAD

**Issue by lihugang** [qxchuckle/vsc-cec-ide#45]
如图
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/8417c444-f23b-42d8-b0e7-bde5bc4f0ce4)
插件已经是最新版本的了

![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/ecd438a1-6d61-471c-ba89-f08c4d733200)

**Comment by qxchuckle** [comment]
快速修复么，更新至0.1.4版本看看

**Comment by lihugang** [comment]
@qxchuckle 0.1.4版本也不行
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/9934c67b-20d4-4370-8184-fad481497669)
版本是360bdbfb 今天早上提交的![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/3abf4463-73aa-4512-840d-57197c0b1ebe)

**Comment by qxchuckle** [comment]
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/ec6f9222-d7cf-4f31-9fd6-c5964b1eeba0)
我这里是正常的，我将进行排查

**Comment by qxchuckle** [comment]
> @qxchuckle 0.1.4版本也不行 ![image](https://user-images.githubusercontent.com/94808542/264208317-9934c67b-20d4-4370-8184-fad481497669.png) 版本是360bdbfb 今天早上提交的![image](https://user-images.githubusercontent.com/94808542/264208384-3abf4463-73aa-4512-840d-57197c0b1ebe.png)

在最新的推送中我尝试修复了这个问题，你可以拉取测试

**Comment by lihugang** [comment]
好像还是不行？
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/7b4849f5-bccd-41d8-9385-688f44ad57ed)

**Comment by qxchuckle** [comment]
> 好像还是不行？

待我翻翻微软的文档，你的vscode是1.81版本的吗

**Comment by lihugang** [comment]
是
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/7a23860b-ea6f-46ae-b825-958d41df716b)

**Comment by qxchuckle** [comment]
那就奇怪了，得去看看文档了，其它开发者也能显示出快速修复，但我也注意到还有不少人没有快速修复

**Comment by qxchuckle** [comment]
在最新的推送中我修复了这个问题，你可以拉取测试
问题出在{ scheme: 'file' }我将其改为{ scheme: '*' }以解决问题

**Comment by lihugang** [comment]
好，谢谢
