### ISSUE TITLE
敏感词检测过于敏感（doge

### ISSUE THREAD

**Issue by YUMEYA** [qxchuckle/vsc-cec-ide#48]
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/17715365/3694c990-b187-4b8b-957d-e89bc006796e)
如图，建议优化为全词匹配

**Comment by RJQingHuan** [comment]
就这样挺好的

**Comment by RJQingHuan** [comment]
防止别人钻空子

**Comment by qxchuckle** [comment]
你可以试试自定义敏感词，在敏感词两边加上空格，匹配时就是按词匹配了

**Comment by qxchuckle** [comment]
目前使用的词库较为严格，后续会优化默认词库

**Comment by qxchuckle** [comment]
我将会优化敏感词的匹配，若敏感词是纯英文，将按单词匹配

**Comment by qxchuckle** [comment]
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/d2207c14-f5d6-40b4-8da7-9c6a79910523)
在最新的仓库代码已优化该问题

**Comment by lihugang** [comment]
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/1159c1c0-fd70-41de-a784-a4ecab07fb70)
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/77eb81fe-5803-444d-9425-c152e9bef95f)
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/fd92f3f8-4670-4bab-8c91-023b578ed1f7)

**Comment by qxchuckle** [comment]
> &

![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/c1905144-b9aa-45c2-a1ce-344019b44509)
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/69f11a65-7a65-40ab-90f6-bcb8611ad6d2)


所以词库还需要优化，用的是https://github.com/cjh0613/tencent-sensitive-words
但词库这玩意，不加密扔仓库。。。不太好，都是敏感词

**Comment by qxchuckle** [comment]
> > > & item 为什么会是敏感词啊😭
> > 
> > 
> > 有没有好用的词库😭这个确实太严格了，历史人物基本上都是敏感词。。
> 
> 自己改改吧，这玩意毕竟太敏感了，大家都不敢发出来😭

删了很多网址类敏感词了，还有2w7千行。。。也就是2w7千个😭

**Comment by qxchuckle** [comment]
> > > > > & item 为什么会是敏感词啊😭
> > > > 
> > > > 
> > > > 有没有好用的词库😭这个确实太严格了，历史人物基本上都是敏感词。。
> > > 
> > > 
> > > 自己改改吧，这玩意毕竟太敏感了，大家都不敢发出来😭
> > 
> > 
> > 删了很多网址类敏感词了，还有2w7千行。。。也就是2w7千个😭
> 
> lan'wei'lou 居然不是敏感词

这就加上（

**Comment by lihugang** [comment]
red-health-code 也不是.......

github会被搜索引擎索引到，不敢发敏感词

**Comment by qxchuckle** [comment]
> 

我再看看有没有私人维护的敏感词。。。

**Comment by qxchuckle** [comment]
@lihugang 
![2f927fb37bed122d07c5e7b6ed3af61](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/15c41eeb-4cd9-4738-8b8c-59026c353bf6)
这个功能你有啥头绪不，我不咋会TS体操（

**Comment by lihugang** [comment]
这图是P的吧......

**Comment by lihugang** [comment]
> 这个功能你有啥头绪不，我不咋会TS体操（

其实我也不怎么会类型体操，最多就只写过个五六行的体操(>﹏<) 比不上那位用ts类型系统来写lisp解析器的

所以，把嵌套中的Awaited/ReturnType/typeof这些简单的方法去掉，剩下的如果层数超过三个就弹广告>_<

**Comment by lihugang** [comment]
@qxchuckle 我觉得可以把ts的类型备案弄成写测试样例

这样既整了活又实用能保证代码质量

**Comment by Eronana** [comment]
可以尝试用分词+布隆过滤器来做敏感词检测, 来避免词库出现敏感词.
