### ISSUE TITLE
没有找到会员入口，没有实名制人脸验证登录环节

### ISSUE THREAD

**Issue by Yifeeeeei** [qxchuckle/vsc-cec-ide#5]
没有人脸验证太不安全了😡
没法充会员怎么花经费😡

**Comment by qxchuckle** [comment]
正在完成会员功能，这是国产化必不可少的核心技术，为了使其更加显眼，我将会将会员界面移动至侧边栏固定入口

**Comment by snowman** [comment]
未登录用户:
1. 打开文件只能只读方式打开
2. 代码无高亮

普通用户:
1. 登录享免费编辑
2. 每天可免费保存 `10` 次
3. 显示菜单栏

`VIP 1` 只需 ￥9.9/月, 尊享权限:
1. 无限次数保存
2. 代码高亮
3. 支持 插件功能
4. 支持 打开文件夹

`VIP 2` 只需 ￥19.9/月, 尊享权限:
1. 支持 撤销操作
2. 支持 搜索功能
3. 支持 多标签
4. 支持 调试 功能
5. 支持 Command Palette
