### ISSUE TITLE
[feature request] 公文模板

### ISSUE THREAD

**Issue by lihugang** [qxchuckle/vsc-cec-ide#51]
建议加入公文模板功能，在侧边栏选择喜欢的模板，然后就可以用vscode写公文了。（格式是 LaTeX ）

这下 **真·自主创新** 了

**Comment by qxchuckle** [comment]
这玩意多用word写吧，而且问gpt就行了，暂时不考虑

**Comment by lihugang** [comment]
> 这玩意多用word写吧，而且问gpt就行了，暂时不考虑

技术人员用什么word🤣 而且gpt写公文的能力好像不太行，还是要模板比较好

**Comment by lihugang** [comment]
话说ts类型备案那个功能怎么样了，我好久没看了

**Comment by qxchuckle** [comment]
> 话说ts类型备案那个功能怎么样了，我好久没看了

![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/4c15b918-eec4-4613-a47e-27af114b7399)
注释了，没实装，感觉和预想的不太一样，功能上没有清晰用途的指向（

**Comment by lihugang** [comment]
其实功能的话我感觉可以弄成对类型的**单元测试**，但实现太累了，几乎变成写半个ts编译器了，我肯定写成**屎山**了，而且**性能**估计也好不到哪里去

**Comment by lihugang** [comment]
我去弄个公文的**LaTeX**模板？

**Comment by qxchuckle** [comment]
你加吧，类似这种？点击后就插入当当前编辑器光标位置么？
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/12f4419b-af37-426a-865c-678271532a5d)

**Comment by lihugang** [comment]
这种挺好的，就是模板文件有点大，我想弄成点击后就新打开一个标签页填充好模板内容

**Comment by qxchuckle** [comment]
> 这种挺好的，就是模板文件有点大，我想弄成点击后就新打开一个标签页填充好模板内容

都行，这样加个右键也不错，点击后就弹出选择
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/0c70569a-0d4b-4715-8399-fc6bcdf05c3e)

**Comment by qxchuckle** [comment]
> 这种挺好的，就是模板文件有点大，我想弄成点击后就新打开一个标签页填充好模板内容

可以选择后再弹个选择，是插入到当前活动编辑器光标处还是新打开一个编辑器
