### ISSUE TITLE
[Feature Request] 希望软件图标兼容 macOS

### ISSUE THREAD

**Issue by maxela-2001** [qxchuckle/vsc-cec-ide#58]
如题，目前 Repo 中的 App 图标只兼容 Windows .ico 图标，希望对 macOS .icns 加以兼容。

**Comment by lihugang** [comment]
这个可以用嘛，我没有macos测试，如果可以的话我就发个pr提交这个图标，谢谢
[CEC-IDE.zip](https://github.com/qxchuckle/vsc-cec-ide/files/12474707/CEC-IDE.zip)

**Comment by lihugang** [comment]
[CEC-IDE (1)-6.zip](https://github.com/qxchuckle/vsc-cec-ide/files/12474936/CEC-IDE.1.-6.zip)
那这个呢

**Comment by maxela-2001** [comment]
看起来是专为旧版CEC-IDE打造（没有圆角矩形背景）的图标。
不过总比没有强，我觉得可以提交下。
<img width="820" alt="image" src="https://github.com/qxchuckle/vsc-cec-ide/assets/69588357/1617cc4e-12b5-4429-b95d-7c5daadd4a92">

**Comment by lihugang** [comment]
ok，可以关掉这个 issue 了

**Comment by maxela-2001** [comment]
适配方法我也附一份吧：

1. Finder 打开 Applications 文件夹并找到 VSCode，右键选择 Get Info
<img width="554" alt="image" src="https://github.com/qxchuckle/vsc-cec-ide/assets/69588357/ee85328a-02a5-4ede-9ec2-0f8b29dadab5">
2. 将 .icns 文件拖入应用图标
<img width="297" alt="Screenshot 2023-08-30 at 7 40 59 pm" src="https://github.com/qxchuckle/vsc-cec-ide/assets/69588357/66260758-0027-4bc9-b1ea-5a62cda534ff">

3. 如应用到 Dock 栏，重启 VSCode

复原：在 VSCode 安装目录以下路径找到 Code.icns，同上述步骤
<img width="828" alt="image" src="https://github.com/qxchuckle/vsc-cec-ide/assets/69588357/e3d184e2-b666-4674-bedc-280b266078b8">

**Comment by lihugang** [comment]
> 适配方法我也附一份吧：
> 
> 1. Finder 打开 Applications 文件夹并找到 VSCode，右键选择 Get Info
> 
> <img alt="image" width="554" src="https://user-images.githubusercontent.com/69588357/264328215-ee85328a-02a5-4ede-9ec2-0f8b29dadab5.png">
> 2. 将 .icns 文件拖入应用图标
> 
> <img alt="Screenshot 2023-08-30 at 7 40 59 pm" width="297" src="https://user-images.githubusercontent.com/69588357/264330501-66260758-0027-4bc9-b1ea-5a62cda534ff.png">
> 3. 如应用到 Dock 栏，重启 VSCode
> 
> 复原：在 VSCode 安装目录以下路径找到 Code.icns，同上述步骤 <img alt="image" width="828" src="https://user-images.githubusercontent.com/69588357/264329741-e3d184e2-b666-4674-bedc-280b266078b8.png">

发 pr 提交到 README.md 上吧，发这没有人能找得到的😅
