### ISSUE TITLE
Ubuntu提示国产化失败呢

### ISSUE THREAD

**Issue by sleichu2** [qxchuckle/vsc-cec-ide#63]
![img_v2_fadd4234-e20a-4498-8b44-2e2b2d651cfg](https://github.com/qxchuckle/vsc-cec-ide/assets/47548399/1a965f76-5b20-4276-ae8e-2d9772be739b)
但是有些国产化元素也能加上。

**Comment by qxchuckle** [comment]
目前编辑器的ui是什么状态，左上角图标替换成功了么，能否提供截图

**Comment by sleichu2** [comment]
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/47548399/251932d5-2a50-4715-926a-5d183e6c7b8e)
这样的，感觉该有的也差不多了

**Comment by qxchuckle** [comment]
这些是不用输入命令都有的，看起来是ubuntu上vsc的结构和win上的不太一样，所以没办法改ui的一些内容🤔
