### ISSUE TITLE
国产化完后不用管理员打开会报这个错误

### ISSUE THREAD

**Issue by zhangjingxian1998** [qxchuckle/vsc-cec-ide#68]
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/81813465/1919d451-63bd-4569-aba7-74d60f54f8db)

**Comment by qxchuckle** [comment]
请试着等待vscode及其扩展完全加载完毕再点击侧边栏的cecide图标

**Comment by qxchuckle** [comment]
0.2.4尝试修复了该问题
