### ISSUE TITLE
老冯啊，这国产化IDE，大伙都不敢用啊。

### ISSUE THREAD

**Issue by Moe-hacker** [qxchuckle/vsc-cec-ide#69]
我听有人说，说是有人在这国产软件里面下了jianshi用户隐私的后门啊，但凡多输入一个敏感词就会爆炸啊，况且这会员制国产IDE的VIP啊，逝分滴珍贵，甚至九分滴珍贵，实在是泰库辣，我一个小萌新，怎么能用这珍贵滴IDE呢，还是大家先用吧。

**Comment by qxchuckle** [comment]
用，tnnd，为什么不用！

**Comment by TIANLI0** [comment]
tnnd，为什么不用！

**Comment by Snoopy1866** [comment]
既然大家都知道了，这戏我就不演了，我就是大名鼎鼎的国内首款和自主研发高级开发工具，代号“CEC-IDE”，这后门，是我放的，你们不用，也别想活着！！！

**Comment by Moe-hacker** [comment]
> 既然大家都知道了，这戏我就不演了，我就是大名鼎鼎滴国内首款和自主研发高级开发工具，代号“CEC-IDE”，这后门，是我放滴，你们不用，也别想活着！！！

事国内首款和自主研发双料会员制高级开发工具(迫真)
