### ISSUE TITLE
征集实用功能建议

### ISSUE THREAD

**Issue by qxchuckle** [qxchuckle/vsc-cec-ide#70]
要有国产化特色的，要实用的。

**Comment by BakaJzon** [comment]
实名认证，防沉迷，隐私协议暗藏玄机

**Comment by Rlxzmdd** [comment]
加个标语公告栏

部份标语参考：
坚定不移地维护中国共产党领导！
坚持党领导IDE！
坚持党指挥代码！

**Comment by Rlxzmdd** [comment]
1. 政务相关假数据填充
这个确实有点用处，比如一些标语填充，政务文章填充之类的。在开发政务相关的程序可以用到。

2. 政府语料库
同上类似，可以建立一个快捷的党政语料库，方便快速填入代码中，省的到处翻。

**Comment by qpdk777** [comment]
当务之急是赶紧兼容原神

**Comment by zhangjingxian1998** [comment]
> 当务之急是赶紧兼容原神

我超，原

**Comment by zhheo** [comment]
青少年防沉迷弹窗

**Comment by LeoXing1996** [comment]
扫 码 登 录

**Comment by qinlili23333** [comment]
开屏摇一摇广告

**Comment by fireMan-34** [comment]
考公资料库
公务日期

**Comment by SteveZMTstudios** [comment]
允许修改用户图标和重定义“续费会员”按钮的执行方式。

**Comment by SteveZMTstudios** [comment]
> 允许修改用户图标和重定义“续费会员”按钮的执行方式。

比如重定向到特定链接或者执行自定义cmd命令或弹窗自定义文本（

**Comment by qxchuckle** [comment]
> 青少年防沉迷弹窗

已实装青少年防沉迷模式

**Comment by qxchuckle** [comment]
> 允许修改用户图标和重定义“续费会员”按钮的执行方式。

已允许自定义侧边栏头像，按钮执行方式暂不考虑自定义，主要是没法给用户提供一个配置去实现

**Comment by qxchuckle** [comment]
> 开屏摇一摇广告

很显然，你不会想抱着电脑摇摆

**Comment by qxchuckle** [comment]
> 当务之急是赶紧兼容原神

已加入未来的计划

**Comment by qxchuckle** [comment]
> 实名认证，防沉迷，隐私协议暗藏玄机

已实装防沉迷模式

**Comment by JasonMo1** [comment]
禁止调用未备案的函数

**Comment by PlayMcBKuwu** [comment]
> > 允许修改用户图标和重定义“续费会员”按钮的执行方式。
> 
> 已允许自定义侧边栏头像，按钮执行方式暂不考虑自定义，主要是没法给用户提供一个配置去实现

- 可以设置为打开网页或者以 CMD / 终端执行命令

**Comment by lihugang** [comment]
#51

**Comment by lihugang** [comment]
加入收集各地政府办事网站的黄页/指南，便于查找（要是能直接在CEC-IDE查询办事进度就更好了，但我看要真实现的话得进去）

**Comment by lihugang** [comment]
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/b2e5e350-8272-415c-b2db-0693eca39697)
建议在这里再加一条：实名：张*三

**更有那味了**

**Comment by qinlili23333** [comment]
> > 开屏摇一摇广告
> 
> 很显然，你不会想抱着电脑摇摆

Surface可以摇，有传感器，用js接口去调灵敏度没啥问题

**Comment by lihugang** [comment]
> 开屏摇一摇广告

感觉不如这个 更创新 更有特色
![IMG_7486](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/8b662c1e-19df-408a-83ee-07ed781f9b82)

**Comment by qxchuckle** [comment]
> > > 开屏摇一摇广告
> > 
> > 
> > 很显然，你不会想抱着电脑摇摆
> 
> Surface可以摇，有传感器，用js接口去调灵敏度没啥问题 [sensor-js.xyz/demo.html](https://sensor-js.xyz/demo.html) 这个页面在Surface上的Chrome里正常工作，Electron里应该也可以跑

很显然，我晃了一分钟的笔记本电脑，也没有看到参数有任何变化（

**Comment by qxchuckle** [comment]
> > > 开屏摇一摇广告
> > 
> > 
> > 很显然，你不会想抱着电脑摇摆
> 
> Surface可以摇，有传感器，用js接口去调灵敏度没啥问题 [sensor-js.xyz/demo.html](https://sensor-js.xyz/demo.html) 这个页面在Surface上的Chrome里正常工作，Electron里应该也可以跑

亮一亮是个不错的方案，毕竟大部分电脑都有相对应的传感器（bushi

**Comment by qinlili23333** [comment]
> 很显然，我晃了一分钟的笔记本电脑，也没有看到参数有任何变化（


可以做成检测到存在传感器则使用摇一摇，针对有传感器的二合一设备，传感器不存在则使用亮一亮

**Comment by MarcusYYDS** [comment]
检测鼠标移动啊(

**Comment by qinlili23333** [comment]
> > 很显然，我晃了一分钟的笔记本电脑，也没有看到参数有任何变化（
> 
> 可以做成检测到存在传感器则使用摇一摇，针对有传感器的二合一设备，传感器不存在则使用亮一亮

我已经在自己的开屏广告组件里支持摇一摇了
https://github.com/qinlili23333/HamoodSplash

**Comment by xuning888** [comment]
增加青年大学习

**Comment by wqshmzh** [comment]
可以尝试以下改进：
1、把VSCode的帮助菜单里的“关于”对话框改成CEC-IDE相关的信息
2、在左侧面板中添加“已通过实名验证”的相关标识
3、增加几个虚构的软件备案号

**Comment by MrZ626** [comment]
> > 开屏摇一摇广告
> 
> 很显然，你不会想抱着电脑摇摆

那可以做成启动后几秒钟内鼠标移动幅度过阈值触发

**Comment by zhbgaoshou** [comment]
编码两小时，看五分钟广告
