### ISSUE TITLE
添加修改CEC侧栏用户名等信息的设置

### ISSUE THREAD

**Issue by MrZ626** [qxchuckle/vsc-cec-ide#71]
TheUser和2077看着有点楞啊
既然是学习插件开发那试着加个设置项也很合理吧！
顺便这已经svip了咋还有激活会员按钮，可以改成续费？或者有vip的时候不显示，设置里直接选vip等级这样

**Comment by qxchuckle** [comment]
明天搞（

**Comment by qxchuckle** [comment]
已经可以在设置中进行自定义
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/99ce5e85-044d-41bf-a339-1413da079b90)
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/83defd2b-c2a8-4bd6-8220-759dd487e905)
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/7728109b-089c-4419-99e0-39dd53216494)

**Comment by MrZ626** [comment]
好好好 太快了
