### ISSUE TITLE
添加对远程开发环境的支持（但仅启用敏感词检测），并上架 Open VSX Registry

### ISSUE THREAD

**Issue by dsy4567** [qxchuckle/vsc-cec-ide#72]
可以使用 `context.extension.extensionKind === vscode.ExtensionKind.Workspace` 判断是否为远程开发环境

**Comment by qxchuckle** [comment]
我不太理解远程开发环境，我仅有win本地，你可以尝试克隆仓库内的源码将package.json中"extensionKind": [ "ui" ]改为["ui", "workspace"]，然后f5运行下，看看敏感词功能是否正常

**Comment by dsy4567** [comment]
> 我不太理解远程开发环境，我仅有win本地，你可以尝试克隆仓库内的源码将package.json中"extensionKind": [ "ui" ]改为["ui", "workspace"]，然后f5运行下，看看敏感词功能是否正常

GitHub Codespaces 和 [code-server](https://github.com/coder/code-server) 都算远程开发环境

**Comment by qxchuckle** [comment]
#39

**Comment by qxchuckle** [comment]
让我在GitHub Codespaces上安装试试

**Comment by dsy4567** [comment]
检测到remote环境可以拒绝替换文件

**Comment by qxchuckle** [comment]
目前我是让插件强制安装在本地，我将试试如何配置，让插件优先安装在本地，但也可以安装在远端

**Comment by qxchuckle** [comment]
0.2.6已经添加对远程开发环境的支持

**Comment by qxchuckle** [comment]
经过测试，在GitHub Codespaces 上，敏感词检测功能正常

**Comment by qxchuckle** [comment]
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/803a6573-b1cf-433c-80e4-0be61e3173c2)

**Comment by qxchuckle** [comment]
已上架Open VSX，https://open-vsx.org/extension/qcqx/cec-ide
