### ISSUE TITLE
遥遥领先

### ISSUE THREAD

**Issue by 1823616178** [qxchuckle/vsc-cec-ide#74]
遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先

**Comment by majoson-chen** [comment]
遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先

**Comment by Muska-Ami** [comment]
遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先

**Comment by XiaoNianPoPo** [comment]
遥遥领先遥遥领先

**Comment by 0use-TE** [comment]
遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先遥遥领先
