### ISSUE TITLE
标题栏未修改

### ISSUE THREAD

**Issue by SteveZMTstudios** [qxchuckle/vsc-cec-ide#75]
如图
![屏幕截图 2023-09-06 165418](https://github.com/qxchuckle/vsc-cec-ide/assets/98326195/45230bdb-1a87-49ea-834a-424167d377a3)

![屏幕截图 2023-09-06 165734](https://github.com/qxchuckle/vsc-cec-ide/assets/98326195/08fc747f-a206-4bf9-8366-39b116476844)
（启用了cecide）
![屏幕截图 2023-09-06 165936](https://github.com/qxchuckle/vsc-cec-ide/assets/98326195/b98a441b-3532-4184-8850-9709a5a23c0e)
（未启用）

（如果无法修改请close as not planned.)

**Comment by SteveZMTstudios** [comment]
哦日期还没有格式化检测（

**Comment by qxchuckle** [comment]
标题栏会在后续尝试进行修改，之没注意到，我那块一直放的是命令中心

**Comment by SteveZMTstudios** [comment]
好的awa

**Comment by qxchuckle** [comment]
> 还有即使停用了cec-ide，侧边栏的cec选项66仍然存在

侧边栏图标和敏感词检测功能是安装插件后就存在的，国产化命令只是修改ui样式

**Comment by qxchuckle** [comment]
> 还有即使停用了cec-ide，侧边栏的cec选项66仍然存在

你可以手动右键侧边栏，取消cec-ide图标的显示
