### ISSUE TITLE
icon is not changed

### ISSUE THREAD

**Issue by SeimoDev** [qxchuckle/vsc-cec-ide#76]
The ICON on the tab is still VSCode, could you change it as CEC-IDE?
![1694063545059.png](https://x.imgs.ovh/x/2023/09/07/64f96a5769844.png)

**Comment by qxchuckle** [comment]
软件的图标修改插件做不到

请下载仓库内 CEC-IDE.ico 自行右键-属性-更改图标（对于MacOS用户，请使用 CEC-IDE.icns）
