### ISSUE TITLE
设置即时生效

### ISSUE THREAD

**Issue by MrZ626** [qxchuckle/vsc-cec-ide#77]
vsc自带的设置好像很多都是焦点离开设置界面的时候就会刷新生效？~~加一下省得按重启快捷键~~ ~~没啥意义但既然开发练习~~

**Comment by qxchuckle** [comment]
这是个不错的主意，正在将所有设置都改为可热重载的

**Comment by qxchuckle** [comment]
2.8版本已支持设置热重载
