### ISSUE TITLE
防沉迷计时问题

### ISSUE THREAD

**Issue by lihugang** [qxchuckle/vsc-cec-ide#83]
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/fe27eff5-1b9a-475e-a0a7-98a0aaae7aa0)
同时打开多个vscode窗口时，使用时长会被重复计算

如图，插件显示我今天写了18h代码，但显然不可能......

另一个插件显示的时间是：
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/25b351a9-d0c3-4c23-8cb5-3ed172d7c312)

**Comment by qxchuckle** [comment]
暂时修复了这个加倍问题，但是多个编辑器定时器和计数器同时计数挺麻烦，同时打开多个编辑器，显示的时间会有1-2分钟到差距，改天换成直接计算时间戳

**Comment by lihugang** [comment]
昨天没关vscode，现在29h了
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/94808542/3110e50e-35eb-454a-b2c1-f70cf8f2ea29)
这个可以自动重置一下嘛😉
