### ISSUE TITLE
提示code安装损坏，使用checksums命令也没用...

### ISSUE THREAD

**Issue by uf-fipper** [qxchuckle/vsc-cec-ide#9]
如题，我使用 `CEC-IDE` 国产化后，提示 `code` 已损坏，然后我使用 `Fix Checksums: Apply` 命令，重启后依然提示 `code` 已损坏，且再次使用 `Fix Checksums: Apply` 命令后，提示 `No changes to checksums where necessary`
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55644019/c7788619-9efa-45e8-9ee0-444e35ee1997)
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55644019/00c5a201-2007-453a-8c31-d2db30f0c977)

**Comment by qxchuckle** [comment]
请使用管理员模式打开vscode再执行 `Fix Checksums: Apply`

**Comment by uf-fipper** [comment]
依然不生效qwq
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55644019/50876869-b852-4f7e-95b6-ac0a4f12208f)

**Comment by qxchuckle** [comment]
在管理员模式下，先执行 `CEC-IDE-RESTORE` 再执行 `CEC-IDE` 最后执行 `Fix Checksums: Apply` 试试

**Comment by uf-fipper** [comment]
还是一样呜呜
我还试过 `CEC-IDE-RESTORE` 然后 `CEC-IDE` 然后 `Fix Checksums: Restore` 再 `Fix Checksums: Apply` ，也不行

请问提示code已损坏会有什么影响吗

**Comment by qxchuckle** [comment]
你似乎并没有在管理员模式下，正常来说会有管理员标识
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/6f1cc81c-c7c4-408c-82a3-14744e4734c5)
请邮件exe属性勾选以管理员身份运行
![image](https://github.com/qxchuckle/vsc-cec-ide/assets/55614189/fa929ce3-bfa2-4bdd-a250-1de15815e94d)

**Comment by uf-fipper** [comment]
> 你似乎并没有在管理员模式下，正常来说会有管理员标识 ![image](https://user-images.githubusercontent.com/55614189/263574345-6f1cc81c-c7c4-408c-82a3-14744e4734c5.png) 请邮件exe属性勾选以管理员身份运行 ![image](https://user-images.githubusercontent.com/55614189/263574643-fa929ce3-bfa2-4bdd-a250-1de15815e94d.png)

我重新试一下

**Comment by qxchuckle** [comment]
提示code已损坏并不会有任何影响，实际上，这是因为插件修改了vscode一处源码的css文件，但这并不会真的导致vscode损坏

**Comment by uf-fipper** [comment]
我重新下载安装了vscode，以管理员身份运行后执行 `CEC-IDE` 和 `Fix Checksums: Apply`，已经不再提示code损坏了
感谢帮忙！v你50000000000研发经费/doge
