### ISSUE TITLE
[bug]欢迎页头图去哪里了😭

### ISSUE THREAD

**Issue by Wangs-official** [qxchuckle/vsc-cec-ide#96]
<img width="1364" alt="7dd6fa577e49dd388ab836b92e48d7f0" src="https://github.com/user-attachments/assets/db594f3b-23b2-4f87-8991-15a2c38a0d27">

![bcdcf0a1e5dbd71b3d91374c69003073](https://github.com/user-attachments/assets/49a36d64-501e-4ec5-bbc9-0436ac8ec60d)

我的欢迎页头图没了，这样怎么让别人知道我在用cec-ide😭（并不是

vscode版本：
```
版本: 1.92.1 (Universal)
提交: eaa41d57266683296de7d118f574d0c2652e1fc4
日期: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 21.6.0
```

我是macos喵

**Comment by qxchuckle** [comment]
macos是这样的，而win可以用了（没有mac喵，有bug也不知道咋修喵）

**Comment by Wangs-official** [comment]
> mac是这样的，而win可以用了（没有mac喵，有bug也不知道咋修喵）

好的喵
